"""initial schema

Revision ID: 818f54a66d60
Revises: 
Create Date: 2026-05-21 23:10:11.469789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818f54a66d60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('sofor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_soyad', sa.String(length=120), nullable=False),
    sa.Column('tc_kimlik', sa.String(length=11), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tc_kimlik')
    )
    op.create_table('alarm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alarm_turu', sa.String(length=50), nullable=False),
    sa.Column('tarih', sa.DateTime(), nullable=False),
    sa.Column('sofor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sofor_id'], ['sofor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alarm')
    op.drop_table('sofor')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
